### ISSUE TITLE
Configuration path question 🤔  (`app.yml`)

### ISSUE THREAD

**Issue by wangcch** [deepzz0/appdemo#1]
https://github.com/deepzz0/appdemo/blob/v1.0.0/pkg/config/config.go#L49-L50
https://github.com/deepzz0/appdemo/blob/v1.0.0/cmd/demo/main.go#L29-L30

`$GOPATH/src/xxx/xx/appdemo` 感觉用户的中间路径无法确定，
不知道这里 根据 gopath 生成绝对路径是否有必要 🤔

小白思维，不对请指正🙆‍♂️

**Comment by deepzz0** [comment]
考虑不周，这个地方要重新考虑。小伙子可以👍
